version: '3'
services:
  pgsql:
    image: "postgres"
    env_file:
      - .env
    volumes:
      - pgsql-data:/var/lib/postgresql/data/
      - ./sql/init-pgsql.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  mysql:
    image: "mysql"
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/myql/data/
      - ./sql/init-mysql.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
volumes:
  pgsql-data:
  mysql-data:
