
version: '3'

services:
  backend:
    build: backend
    restart: always
    ports: 
      - 8088:8088
    networks:
      - dev_network
    container_name: backend
    volumes:
        - ./data:/data
        - ./backend:/fastapi

  frontend:
    build: frontend
    restart: always
    depends_on:
      - backend
    ports: 
        - 8501:8501
    networks:
      - dev_network
    container_name: frontend
    volumes:
        - ./data:/data
        - ./frontend:/streamlit

networks:
  dev_network:
    driver: bridge

volumes:
  data:
    name: data
  