
version: '3'

services:
  fastapi:
    build: fastapi
    ports: 
      - 8088:8088
    networks:
      - dev_network
    container_name: fastapi
    volumes:
        - ./data:/data

  streamlit:
    build: streamlit
    depends_on:
      - fastapi
    ports: 
        - 8501:8501
    networks:
      - dev_network
    container_name: streamlit
    volumes:
        - ./data:/data

networks:
  dev_network:
    driver: bridge