
version: '3'

services:
  backend:
    build: backend
    ports: 
      - 8088:8088
    networks:
      - dev_network
    container_name: backend
    volumes:
        - ./data:/data

  frontend:
    build: frontend
    depends_on:
      - backend
    ports: 
        - 8501:8501
    networks:
      - dev_network
    container_name: frontend
    volumes:
        - ./data:/data
        - ./frontend:/app

networks:
  dev_network:
    driver: bridge